#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACM "*.php" | tr '\n' ' ')
[ -z "$FILES" ] && exit 0

# 自定义 PHP-CS-Fixer 的安装路径，如果已经将其添加到 PATH，则无需修改
PHP_CS_FIXER="vendor/bin/php-cs-fixer"

# 对暂存文件执行 PHP-CS-Fixer
$PHP_CS_FIXER fix --quiet $FILES

# 将修改后的文件重新暂存
git add $FILES

exit 0
