ingress:
  enabled: true
  hosts:
    - host: { 域名 }
      paths:
        - path: /{路径}-dev
          pathType: ImplementationSpecific
  tls:
    - secretName: blue-dot.com.cn
      hosts:
        - blue-dot.com.cn
